language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script: "./gradlew clean shadowJar"
deploy:
  provider: releases
  api_key:
    secure: gJ/0q6RKfmfZa/QLIdEd+vYwK89NL/SGyj0nxCXmRTmqZBqUhcxacWo2KOOmud3o0cYZhehKdRmD6tayRFBz/flgGvX4r9NmI18vpFsX5KuaraaCXG6Wisisobn6d7RL19FZ+xufiK+GCgYR3/d7laGxIF0nIyXPp4rWlGes3TlY3rZe97OCzgYmN+jhX4h9SWlNwtJqAZr7t9+yIPe3/d6LPoyLJCQvyc5Ra643GDsGnjJi2H2QZ16eij0Fj4vkIWAp9pZQpOzf32lqYtGTu9s1MavLT9UVeMXs2tTzdDIscvzN4zhVANrBeNtiU/ElaHSULn/0PJ/HIWI8Pl63sp9mhw/00cbrSvIEJjemwafSq9YSI5rLo4TnA8d9buvdSgjMSFAyek7xW4DfSU1R8SEh/Y7g4InWolWdmBi3h4r7a6S7MBCFGw3bpvQR+fn3AIOZ1VNMS8aEEIQ6tcqnKf597SKEfoOdcisK74FRPZOBhNbMsVGORzd/tabDzYRUtBQp52FPdNw329YSwqsmsW9Ta9AvnOI3IwwDU8tU+Fb97r/V01kKGH5LxRB3N9InfoyVzQuiVAGEJSrjYWt15DWlBof7Oi1eUkGIgNO92B+HpkHvdcXBZT4tX4pcwjurbtHyHcSE4t5xsmBBNzwn1zTsXI7cocUKzIk5Eiw+8lo=
  file: build/libs/minecraft-amongus-1.0-SNAPSHOT-dist.jar
  on:
    repo: parangee/minecraft-amongus-plugin
  skip_cleanup: 'true'
