language: java
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script: "./gradlew clean shadowJar"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/libs/minecraft-amongus-1.0-SNAPSHOT-dist.jar
  on:
    repo: parangee/minecraft-amongus-plugin
  skip_cleanup: 'true'
